on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release --nologo ./src/Lumina.sln
    - name: dotnet test
      run: dotnet test --configuration Release --nologo ./src/Lumina.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: |
          ./src/Lumina/bin/Release/*.nupkg
          ./src/Lumina/bin/Release/*.snupkg
          ./src/Lumina/bin/Release/**/Lumina.dll
          ./src/Lumina/bin/Release/**/Lumina.pdb
          ./src/Lumina/bin/Release/**/Lumina.deps.json
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Lumina ${{ github.ref }}
        draft: false
        prerelease: false
    - name: add build artifact to release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: Lumina.${{ github.ref }}.zip
        asset_path: ./Lumina.${{ github.ref }}.zip
        asset_content_type: application/zip
    - name: publish nuget package
      # for some cursed reason this fails on windows ???????????
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' }}
      run: dotnet nuget push ./src/Lumina/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate